"""Write a deterministic content manifest for the paper's evidence snapshot.

The manifest identifies a dirty-but-reviewable candidate by hashes of every
producer/input source and every evidence artifact; it does not guess historical
package versions from file dates.

The manifest is a release-time snapshot, not a live view: it is regenerated by
running this script, and `paper/src/check-provenance.py` fails if the tree has
moved since.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "evidence" / "provenance.json"

SOURCE_SCOPE = (
    "Cargo.toml",
    "Cargo.lock",
    "crates/**/*.toml",
    "crates/**/*.rs",
    "crates/sharpearena-py/python/**/*.py",
    "paper/src/*.py",
    "paper/main.tex",
    "paper/sections/*.tex",
    "paper/refs.bib",
)

ARTIFACT_SCOPE = ("paper/evidence/*.json", "paper/figures/*.pdf")
MODEL_ARTIFACT_SCOPE = ("paper/evidence/model-artifacts/*.json",)
MODEL_IDENTITY_FIELDS = (
    "model",
    "digest",
    "quantization",
    "server",
    "server_version",
)

# `crates/**/*.rs` otherwise matches machine-local build outputs under
# `crates/*/target/**/build/*/out/*.rs`, which are neither source nor
# reproducible across machines.
EXCLUDED_DIR_NAMES = ("target", ".venv", "__pycache__", "node_modules", ".git")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def is_excluded(path: Path) -> bool:
    return any(part in EXCLUDED_DIR_NAMES for part in path.relative_to(ROOT).parts)


def files(patterns: tuple[str, ...]) -> list[Path]:
    found: set[Path] = set()
    for pattern in patterns:
        found.update(
            path
            for path in ROOT.glob(pattern)
            if path.is_file() and not is_excluded(path)
        )
    return sorted(found, key=lambda path: path.as_posix())


def records(paths: list[Path]) -> list[dict[str, str]]:
    return [
        {"path": path.relative_to(ROOT).as_posix(), "sha256": sha256(path)}
        for path in paths
    ]


def model_artifact_records(paths: list[Path]) -> list[dict]:
    """Bind model identity files and expose their load-bearing fields.

    Each file uses the same object-or-array shape accepted by
    ``load_identity_manifest``.  The file digest binds every field; the summary
    keeps model/checkpoint identity visible to a provenance reader without making
    them open each nested artifact.
    """

    output: list[dict] = []
    seen_models: set[str] = set()
    for path in paths:
        payload = json.loads(path.read_text(encoding="utf-8"))
        identities = payload if isinstance(payload, list) else [payload]
        if not identities or not all(isinstance(item, dict) for item in identities):
            raise ValueError(f"{path.relative_to(ROOT)} must contain an identity object or array")
        summaries = []
        for index, identity in enumerate(identities):
            missing = [
                field
                for field in MODEL_IDENTITY_FIELDS
                if not isinstance(identity.get(field), str)
                or not identity[field].strip()
                or identity[field].strip().lower() in {"unknown", "unresolved"}
            ]
            if missing:
                raise ValueError(
                    f"{path.relative_to(ROOT)} identity {index} lacks explicit fields: {missing}"
                )
            model = identity["model"]
            if model in seen_models:
                raise ValueError(f"duplicate model identity across provenance files: {model}")
            seen_models.add(model)
            summaries.append({field: identity[field] for field in MODEL_IDENTITY_FIELDS})
        output.append(
            {
                "path": path.relative_to(ROOT).as_posix(),
                "sha256": sha256(path),
                "identities": summaries,
            }
        )
    return output


source_records = records(files(SOURCE_SCOPE))
snapshot = hashlib.sha256(
    "".join(f"{item['sha256']}  {item['path']}\n" for item in source_records).encode()
).hexdigest()

artifacts = records([path for path in files(ARTIFACT_SCOPE) if path != OUT])
model_artifacts = model_artifact_records(files(MODEL_ARTIFACT_SCOPE))

head = subprocess.check_output(
    ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
).strip()
dirty = bool(
    subprocess.check_output(
        ["git", "status", "--porcelain"], cwd=ROOT, text=True
    ).strip()
)

manifest = {
    "schema_version": 4,
    # A manifest cannot contain the hash of the commit that will contain the
    # manifest without becoming self-referential.  Record the commit this
    # generation ran at honestly, together with whether the tree was dirty;
    # source_snapshot_sha256 binds the candidate's actual (possibly
    # not-yet-committed) source bytes.
    "generated_at_head": head,
    "generated_at_head_dirty": dirty,
    "source_snapshot_sha256": snapshot,
    "source_snapshot_scope": list(SOURCE_SCOPE),
    "source_snapshot_excludes": list(EXCLUDED_DIR_NAMES),
    "source_snapshot_scope_note": (
        "Globs are expanded from the repository root; any path with a component "
        "in source_snapshot_excludes is skipped, so build outputs and virtual "
        "environments are not part of the source snapshot."
    ),
    "artifact_scope": list(ARTIFACT_SCOPE),
    "model_artifact_scope": list(MODEL_ARTIFACT_SCOPE),
    "model_identity_fields": list(MODEL_IDENTITY_FIELDS),
    "reproduction_entrypoint": "commands in paper/sections/A-commands.tex",
    "validator": "paper/src/check-provenance.py",
    "source_files": source_records,
    "artifacts": artifacts,
    "model_artifacts": model_artifacts,
}
OUT.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(
    f"wrote {OUT.relative_to(ROOT)}: {len(source_records)} sources, "
    f"{len(artifacts)} artifacts, {len(model_artifacts)} model artifact manifests"
)
