"""Write a deterministic content manifest for the paper's evidence snapshot.

The manifest identifies a dirty-but-reviewable candidate by hashes of every
producer/input source and every evidence artifact; it does not guess historical
package versions from file dates.

The manifest is a release-time snapshot, not a live view: it is regenerated by
running this script, and `paper/src/check-provenance.py` fails if the tree has
moved since. Both scripts share `provenance_common.py`, so the validator applies
exactly the rules the writer applied.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from provenance_common import (  # noqa: E402
    EXCLUDED_DIR_NAMES,
    MODEL_IDENTITY_FIELDS,
    expand,
    head_commit,
    identity_summaries,
    repo_root,
    sha256,
    snapshot_digest,
    working_tree_dirty,
)


ROOT = repo_root()
OUT = ROOT / "paper" / "evidence" / "provenance.json"

SOURCE_SCOPE = (
    "Cargo.toml",
    "Cargo.lock",
    "crates/**/*.toml",
    "crates/**/*.rs",
    "crates/sharpearena-py/python/**/*.py",
    "paper/src/*.py",
    "paper/main.tex",
    "paper/sections/*.tex",
    "paper/refs.bib",
)

ARTIFACT_SCOPE = ("paper/evidence/*.json", "paper/figures/*.pdf")
MODEL_ARTIFACT_SCOPE = ("paper/evidence/model-artifacts/*.json",)

EXCLUDES = frozenset(EXCLUDED_DIR_NAMES)


def files(patterns: tuple[str, ...]) -> list[Path]:
    return expand(patterns, ROOT, EXCLUDES)


def records(paths: list[Path]) -> list[dict[str, str]]:
    return [
        {"path": path.relative_to(ROOT).as_posix(), "sha256": sha256(path)}
        for path in paths
    ]


def model_artifact_records(paths: list[Path]) -> list[dict]:
    """Bind model identity files and expose their load-bearing fields.

    Each file uses the same object-or-array shape accepted by
    ``load_identity_manifest``.  The file digest binds every field; the summary
    keeps model/checkpoint identity visible to a provenance reader without making
    them open each nested artifact.
    """

    output: list[dict] = []
    seen_models: set[str] = set()
    for path in paths:
        payload = json.loads(path.read_text(encoding="utf-8"))
        try:
            summaries = identity_summaries(payload, MODEL_IDENTITY_FIELDS)
        except ValueError as error:
            raise ValueError(f"{path.relative_to(ROOT)} {error}") from error
        for summary in summaries:
            model = summary["model"]
            if model in seen_models:
                raise ValueError(f"duplicate model identity across provenance files: {model}")
            seen_models.add(model)
        output.append(
            {
                "path": path.relative_to(ROOT).as_posix(),
                "sha256": sha256(path),
                "identities": summaries,
            }
        )
    return output


source_records = records(files(SOURCE_SCOPE))
snapshot = snapshot_digest(source_records)

artifacts = records([path for path in files(ARTIFACT_SCOPE) if path != OUT])
model_artifacts = model_artifact_records(files(MODEL_ARTIFACT_SCOPE))

head = head_commit(ROOT)
dirty = working_tree_dirty(ROOT)
if dirty is None:
    raise SystemExit("cannot determine whether the working tree is dirty; is this a git checkout?")

manifest = {
    "schema_version": 5,
    # A manifest cannot contain the hash of the commit that will contain the
    # manifest without becoming self-referential.  Record the commit this
    # generation ran at honestly, together with whether the tree was dirty;
    # source_snapshot_sha256 binds the candidate's actual (possibly
    # not-yet-committed) source bytes.
    "generated_at_head": head,
    "generated_at_head_dirty": dirty,
    "digest_convention": "sha256 over file bytes with CRLF collapsed to LF; files containing a NUL byte are hashed verbatim",
    "source_snapshot_sha256": snapshot,
    "source_snapshot_scope": list(SOURCE_SCOPE),
    "source_snapshot_excludes": list(EXCLUDED_DIR_NAMES),
    "source_snapshot_scope_note": (
        "Globs are expanded from the repository root; any path with a component "
        "in source_snapshot_excludes is skipped, so build outputs and virtual "
        "environments are not part of the source snapshot."
    ),
    "artifact_scope": list(ARTIFACT_SCOPE),
    "model_artifact_scope": list(MODEL_ARTIFACT_SCOPE),
    "model_identity_fields": list(MODEL_IDENTITY_FIELDS),
    "reproduction_entrypoint": "commands in paper/sections/A-commands.tex",
    "validator": "paper/src/check-provenance.py",
    "source_files": source_records,
    "artifacts": artifacts,
    "model_artifacts": model_artifacts,
}
OUT.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(
    f"wrote {OUT.relative_to(ROOT)}: {len(source_records)} sources, "
    f"{len(artifacts)} artifacts, {len(model_artifacts)} model artifact manifests"
)
