"""Write a deterministic content manifest for the paper's evidence snapshot.

The manifest identifies a dirty-but-reviewable candidate by hashes of every
producer/input source and every evidence artifact; it does not guess historical
package versions from file dates.

The manifest is a release-time snapshot, not a live view: it is regenerated by
running this script, and `paper/src/check-provenance.py` fails if the tree has
moved since.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "evidence" / "provenance.json"

SOURCE_SCOPE = (
    "Cargo.toml",
    "Cargo.lock",
    "crates/**/*.toml",
    "crates/**/*.rs",
    "crates/sharpearena-py/python/**/*.py",
    "paper/src/*.py",
    "paper/main.tex",
    "paper/sections/*.tex",
    "paper/refs.bib",
)

ARTIFACT_SCOPE = ("paper/evidence/*.json", "paper/figures/*.pdf")

# `crates/**/*.rs` otherwise matches machine-local build outputs under
# `crates/*/target/**/build/*/out/*.rs`, which are neither source nor
# reproducible across machines.
EXCLUDED_DIR_NAMES = ("target", ".venv", "__pycache__", "node_modules", ".git")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def is_excluded(path: Path) -> bool:
    return any(part in EXCLUDED_DIR_NAMES for part in path.relative_to(ROOT).parts)


def files(patterns: tuple[str, ...]) -> list[Path]:
    found: set[Path] = set()
    for pattern in patterns:
        found.update(
            path
            for path in ROOT.glob(pattern)
            if path.is_file() and not is_excluded(path)
        )
    return sorted(found, key=lambda path: path.as_posix())


def records(paths: list[Path]) -> list[dict[str, str]]:
    return [
        {"path": path.relative_to(ROOT).as_posix(), "sha256": sha256(path)}
        for path in paths
    ]


source_records = records(files(SOURCE_SCOPE))
snapshot = hashlib.sha256(
    "".join(f"{item['sha256']}  {item['path']}\n" for item in source_records).encode()
).hexdigest()

artifacts = records([path for path in files(ARTIFACT_SCOPE) if path != OUT])

head = subprocess.check_output(
    ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
).strip()
dirty = bool(
    subprocess.check_output(
        ["git", "status", "--porcelain"], cwd=ROOT, text=True
    ).strip()
)

manifest = {
    "schema_version": 3,
    # A manifest cannot contain the hash of the commit that will contain the
    # manifest without becoming self-referential.  Record the commit this
    # generation ran at honestly, together with whether the tree was dirty;
    # source_snapshot_sha256 binds the candidate's actual (possibly
    # not-yet-committed) source bytes.
    "generated_at_head": head,
    "generated_at_head_dirty": dirty,
    "source_snapshot_sha256": snapshot,
    "source_snapshot_scope": list(SOURCE_SCOPE),
    "source_snapshot_excludes": list(EXCLUDED_DIR_NAMES),
    "source_snapshot_scope_note": (
        "Globs are expanded from the repository root; any path with a component "
        "in source_snapshot_excludes is skipped, so build outputs and virtual "
        "environments are not part of the source snapshot."
    ),
    "artifact_scope": list(ARTIFACT_SCOPE),
    "reproduction_entrypoint": "commands in paper/sections/A-commands.tex",
    "validator": "paper/src/check-provenance.py",
    "source_files": source_records,
    "artifacts": artifacts,
}
OUT.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(
    f"wrote {OUT.relative_to(ROOT)}: {len(source_records)} sources, "
    f"{len(artifacts)} artifacts"
)
