//! Emit the engine-output vocabulary the npm package restates, so the restatement can be
//! checked instead of trusted.
//!
//! `npm/sharpearena/src/types.ts` types the engine's JSON shapes for TypeScript consumers.
//! The two *wire contract* types are cross-checked against the published JSON Schemas by
//! `npm/sharpearena/test/conformance.test.js`, but the engine-output enums have no schema to
//! check against: they restate Rust declarations, and TypeScript types are erased before any
//! validator runs. That is the part of ARENA-REVIEW A15 left open, which said closing it
//! "would need a generated contract file rather than a test". This is that file's producer.
//!
//! Two guarantees, and only two:
//!
//! * **Variant drift fails to compile.** Each vocabulary is built through a match with no
//!   wildcard arm, so a variant added to `DistributionMode` or `Regime` stops this test
//!   compiling rather than going unnamed. Same device as the process-event contract.
//! * **Restatement drift fails a test.** The committed artifact is what the npm suite reads,
//!   so a `types.ts` union or interface that disagrees with the engine fails there.
//!
//! What it does *not* establish: `DistributionMode`, `ObservationRichness` and `ScenarioSpec`
//! carry their wire form in serde, so their labels and field names here are the engine's own.
//! `Regime` derives no `Serialize` — its JSON labels are authored in the wasm export layer's
//! `regime_label`, so the labels below are a second authoring of them and only the variant
//! list is derived. `BaselineAgent` is not covered at all: it has no Rust enum anywhere, only
//! a string dispatch in the wasm export layer. See the A15 disposition.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use serde_json::{json, Map, Value};
use sharpearena::{DistributionMode, ObservationRichness, Regime, ScenarioSpec};

const CONTRACT: &str = "contract/engine-enums.v1.json";

/// Set `UPDATE_ENGINE_ENUM_CONTRACT=1` to rewrite the committed artifact after an
/// intentional change. Unset, the test compares and fails.
const UPDATE_ENV: &str = "UPDATE_ENGINE_ENUM_CONTRACT";

fn contract_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(CONTRACT)
}

/// Every `DistributionMode`, under the label serde writes, in declaration order.
///
/// The match is exhaustive with no wildcard arm: a tier added to the enum stops this from
/// compiling, which is the whole point of generating the list instead of typing it.
fn distribution_modes() -> Vec<String> {
    [
        DistributionMode::Calm,
        DistributionMode::Hard,
        DistributionMode::Extreme,
        DistributionMode::CointegratedPairs,
        DistributionMode::RegimeShift,
    ]
    .into_iter()
    .map(|mode| match mode {
        carried @ (DistributionMode::Calm
        | DistributionMode::Hard
        | DistributionMode::Extreme
        | DistributionMode::CointegratedPairs
        | DistributionMode::RegimeShift) => serde_json::to_value(carried)
            .expect("a distribution mode serializes")
            .as_str()
            .expect("its wire form is a string")
            .to_string(),
    })
    .collect()
}

/// Every `Regime`, under the label the JSON surface writes.
///
/// `Regime` derives no `Serialize`, so unlike the modes above the strings are authored here
/// rather than read off the type. The exhaustive match still makes an added variant a
/// compile error, which is the drift a hand-maintained union cannot notice.
fn regimes() -> Vec<String> {
    [Regime::Bull, Regime::Bear, Regime::Chop]
        .into_iter()
        .map(|regime| {
            match regime {
                Regime::Bull => "bull",
                Regime::Bear => "bear",
                Regime::Chop => "chop",
            }
            .to_string()
        })
        .collect()
}

/// The serde field names of a struct, taken from a serialized value rather than restated.
fn serialized_fields<T: serde::Serialize>(value: &T) -> Vec<String> {
    let Value::Object(map) = serde_json::to_value(value).expect("the struct serializes") else {
        panic!("expected a JSON object");
    };
    map.keys().cloned().collect()
}

fn build_contract() -> Value {
    let mut enums = Map::new();
    enums.insert("DistributionMode".into(), json!(distribution_modes()));
    enums.insert("Regime".into(), json!(regimes()));

    let mut structs = BTreeMap::new();
    structs.insert(
        "ObservationRichness",
        serialized_fields(&ObservationRichness::default()),
    );
    structs.insert("ScenarioSpec", serialized_fields(&ScenarioSpec::default()));

    json!({
        "schema_version": 1,
        "note": "Generated by crates/sharpearena/tests/engine_enum_contract.rs. The engine-output \
    vocabulary that npm/sharpearena/src/types.ts restates as TypeScript unions and interfaces, \
    which no published JSON Schema covers (ARENA-REVIEW A15). Regenerate with \
    UPDATE_ENGINE_ENUM_CONTRACT=1; do not hand-edit.",
        "enums": Value::Object(enums),
        "structs": structs,
    })
}

fn rendered() -> String {
    serde_json::to_string_pretty(&build_contract()).expect("the contract renders") + "\n"
}

#[test]
fn the_committed_engine_enum_contract_is_what_this_tree_emits() {
    let path = contract_path();
    let expected = rendered();
    if std::env::var(UPDATE_ENV).is_ok() {
        fs::write(&path, &expected).expect("the contract artifact is writable");
        return;
    }
    let actual = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{} must exist and be readable: {e}", path.display()))
        .replace("\r\n", "\n");
    assert_eq!(
        actual, expected,
        "{CONTRACT} has fallen behind the engine; rerun with {UPDATE_ENV}=1 and check what \
         moved, because npm/sharpearena/src/types.ts is checked against this file"
    );
}

#[test]
fn the_contract_is_not_vacuous() {
    // A generator that emitted nothing would make every consumer's cross-check pass for free.
    let contract = build_contract();
    assert_eq!(
        contract["enums"]["DistributionMode"]
            .as_array()
            .unwrap()
            .len(),
        5
    );
    assert_eq!(contract["enums"]["Regime"].as_array().unwrap().len(), 3);
    assert!(contract["structs"]["ScenarioSpec"]
        .as_array()
        .unwrap()
        .contains(&json!("start_level")));
    assert!(contract["structs"]["ObservationRichness"]
        .as_array()
        .unwrap()
        .contains(&json!("lookback")));
}
