#[path = "../build_support.rs"]
mod build_support;

use build_support::dependency_contract;

const SOURCE: &str = r#"
[package]
name = "sharpearena"
version.workspace = true
[dependencies]
sharpebench-sim = "=0.15.0"
sharpebench-core = "=0.15.0"
sharpebench-protocol = { version = "=0.15.0" }
"#;

const PACKAGED: &str = r#"
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
[package]
name = "sharpearena"
version = "0.24.1"
edition = "2021"
[dependencies.sharpebench-core]
version = "=0.15.0"
[dependencies.sharpebench-protocol]
version = "=0.15.0"
features = []
optional = false
default-features = true
[dependencies.sharpebench-sim]
version = "=0.15.0"
"#;

#[test]
fn source_and_cargo_normalized_manifest_have_one_dependency_identity() {
    assert_ne!(SOURCE, PACKAGED);
    assert_eq!(
        dependency_contract(SOURCE).unwrap(),
        dependency_contract(PACKAGED).unwrap()
    );
    assert_eq!(
        dependency_contract(SOURCE).unwrap(),
        dependency_contract(&SOURCE.replace('\n', "\r\n")).unwrap()
    );
}

#[test]
fn semantic_version_and_feature_changes_move_the_identity() {
    let original = dependency_contract(SOURCE).unwrap();
    for changed in [
        SOURCE.replace("=0.15.0", "=0.16.0"),
        SOURCE.replace(
            "version = \"=0.15.0\" }",
            "version = \"=0.15.0\", default-features = false }",
        ),
        SOURCE.replace(
            "version = \"=0.15.0\" }",
            "version = \"=0.15.0\", features = [\"test-feature\"] }",
        ),
    ] {
        assert_ne!(original, dependency_contract(&changed).unwrap());
    }
    for requirement in ["0.15.0", "=0.15", "=0.15.*", ">=0.15.0"] {
        assert!(dependency_contract(&SOURCE.replace("=0.15.0", requirement)).is_err());
    }
}
