"""SharpeArena — a leak-free, point-in-time arena for trading agents.

This package bundles the native pyo3 binding (``sharpearena.sharpearena_py``) with a
gymnasium-compatible wrapper (:class:`SharpeArenaEnv`) and a PrimeIntellect ``verifiers``
environment (:mod:`sharpearena.verifiers_env`) whose rubric is scored by the real
SharpeBench kernel via :func:`score_run`.

The native binding exchanges the language-agnostic wire JSON at its boundary:
``TradingEnv.reset()`` returns an observation JSON string and ``TradingEnv.step()``
takes a decision JSON string. The pure-Python layers parse/build that JSON.
"""

# Refuse-on-mismatch spec-hash handshake, before anything touches the engine: the
# compiled extension must report the tape-semantics hash this package was generated
# against, or every number it would produce is suspect (a stale .pyd in a dev venv is
# exactly the "wasm from commit A, spec from commit B" failure, on the Python surface).
from . import sharpearena_py as _engine_module
from ._spec_hash import (
    EXPECTED_SPEC_HASH,
    SpecHashMismatch,
    check_spec_hash,
    engine_spec_hash,
)

check_spec_hash(engine_spec_hash(_engine_module))

from .adverse_selection import (
    AdverseSelectionParams,
    AdverseSelectionReport,
    EndogenousImpact,
    Fill,
    MakerMarkout,
    MetaOrder,
    compare_endogenous_arms,
    compare_informed_vs_uninformed,
    fill_markout,
    informed_displacement,
    run_adverse_selection,
)
from .baselines import (
    BEHAVIORAL_POLICIES,
    DispositionEffectPolicy,
    KellyVolTargetPolicy,
    MaxSharpePolicy,
    MinVariancePolicy,
    OverconfidentPolicy,
    leaderboard_markdown,
    run_baselines,
)
from .bench_bridge import BenchBridgeError, compile_benchmark_evidence
from .cascade import LiquidationCascadeEnv, cascade_summary, cascade_survived
from .check_env import check_determinism_across_constructors, check_env
from .checkpoint import CheckpointableEnv, CheckpointState
from .confidence import (
    deflated_sharpe_ci,
    paired_dsr_diff,
    pairwise_significance,
    significance_markdown,
)
from .curriculum import (
    AdaptiveCurriculumEnv,
    AdaptiveScheduler,
    CurriculumEnv,
    regime_curriculum,
)
from .data_blocks import (
    block_windows,
    find_continuous_blocks,
    make_block_env,
    sample_block_window,
)
from .dataset import build_scenario_dataset, seed_ranges_disjoint
from .decision_parser import parse_decision
from .deferred import (
    CATEGORICAL,
    DIRECTION,
    INTERVAL,
    NORMAL,
    POINT,
    PROBABILITY,
    Claim,
    ClaimRejected,
    DeferredDesk,
    LeakedResolution,
    Outcome,
    UnresolvedClaim,
    claims_from_json,
    outcomes_from_series,
    resolve_claims,
    score_claim,
    summarize,
)
from .forecast_contract import (
    BINARY_BRIER,
    BINARY_LOG,
    CATEGORICAL_BRIER,
    CATEGORICAL_LOG,
    DIRECTION_ACCURACY,
    FORECAST_CONTRACT_SCHEMA_VERSION,
    FORECAST_EVIDENCE_SCHEMA_VERSION,
    INTERVAL_SCORE,
    NORMAL_CRPS,
    POINT_ERRORS,
    ForecastContract,
    ForecastContractError,
)
from .forecast_evidence import (
    CANCELLED,
    ELIGIBLE,
    LATE,
    PENDING,
    REJECTED,
    RESOLVED,
    ForecastEvidence,
    ForecastEvidenceError,
    ForecastLedger,
    ForecastResolution,
    ForecastRevision,
    ForecastRunIdentity,
    InformationExposure,
    forecast_evidence_from_json,
    write_forecast_evidence,
)
from .discrete import DiscreteAction
from .ecology import (
    allocate_seats,
    baseline_species,
    classify_outcomes,
    competition_payoffs,
    detect_coalitions,
    liquidity_shocks,
    market_payoffs,
    mutating_innovator,
    population_table,
    regime_shocks,
    replicator_step,
    run_ecology,
    steady_shocks,
)
from .effective_config import (
    EffectiveConfigError,
    check_env_effective_config,
    env_effective_config,
    merge_effective_configs,
    resolved_scenario_seed,
    scenario_fingerprint,
)
from .edge_manifest import (
    DeclaredCandidateLineage,
    IdeaProvenance,
    bind_idea_source,
)
from .eval_seeds import (
    EVAL_SEEDS,
    EVAL_SET_VERSION,
    assert_no_regression,
    evaluate_eval_set,
    sealed_eval_seeds,
)
from .execution import ExecutionEnv, execution_quality, immediate_policy, twap_policy
from .execution_noise import ExecutionNoiseWrapper
from .failure_taxonomy import (
    FailureMode,
    FailureRollup,
    classify_episode_failure,
    rollup_failure_modes,
)
from .forecast import (
    ForecastChannelObservation,
    calibrated_forecast,
    forecast_skill_curve,
)
from .functional import SharpeArenaFuncEnv
from .generalization import (
    cross_regime_transfer,
    evaluate_seeds,
    generalization_gap,
    train_test_seeds,
)
from .gym import SharpeArenaEnv
from .indicators import DEFAULT_INDICATORS, INDICATORS, CausalIndicatorObservation
from .lob_env import LOBMarketEnv, noise_trader_policy, symmetric_quote_policy
from .local_agents import (
    DatasetSpec,
    DecisionResponseError,
    DecisionModel,
    EvidenceJournal,
    FieldCell,
    FieldPlan,
    InferenceOutcome,
    InferenceResult,
    LocalAgentError,
    LocalFieldRunner,
    ModelHttpError,
    ModelIdentity,
    ModelResponseError,
    ModelRunConfig,
    ModelTransportError,
    OllamaClient,
    OpenAICompatibleClient,
    PromptRenderer,
    SamplingConfig,
    load_identity_manifest,
)
from .lookahead_guard import LookaheadGuard, LookaheadViolation, guarded, wrap_policy
from .mandate import (
    Mandate,
    mandate_breach,
    mandate_from_dict,
    mandate_text,
    sample_mandate,
    validate_mandate,
)
from .manipulation import (
    DISCLAIMER,
    AsymmetricResult,
    AsymmetricSchedule,
    BoundaryReport,
    ManipulationParams,
    ManipulationResult,
    SizeResponse,
    asymmetric_round_trip_schedule,
    impact_boundary_sweep,
    momentum_follower_policy,
    pump_and_dump_schedule,
    run_asymmetric_probe,
    run_manipulation_probe,
    size_response,
)
from .market_env import EndogenousMarketEnv
from .market_making import (
    MarketMakingEnv,
    MMParams,
    analytically_optimal_policy,
    closed_form_reference_policy,
    fixed_spread_policy,
    mm_regret,
)
from .metrics import RunMetrics, cost_adjusted_score
from .minari_export import to_minari, to_minari_train_test
from .news import SyntheticNewsObservation, news_series
from .obs_extra import (
    CounterfactualInfo,
    KalmanTrendObservation,
    MultiTimescaleMomentum,
    RollingCovarianceObservation,
    TimeToHorizonObservation,
)
from .pairs import KalmanSpreadObservation, SpreadObservation
from .paper_trading import (
    LIFECYCLE_STATES,
    STATE_FILLED,
    STATE_PREPARED,
    STATE_RECONCILED_ABSENT,
    STATE_RECONCILED_ACCEPTED,
    STATE_SUBMISSION_UNKNOWN,
    AccountSnapshot,
    AlpacaMarketData,
    AlpacaPaperBroker,
    BinancePublicData,
    ForwardEvidenceJournal,
    ForwardWindowIdentity,
    InMemoryPaperBroker,
    LifecycleError,
    LifecycleStore,
    OrderLifecycle,
    PaperAccount,
    PaperOrder,
    PaperRiskConfig,
    PaperRiskGuard,
    PaperTradingSession,
    SubmissionUnknown,
    bind_forward_window,
    forward_window_from_preimage,
    make_forward_commitment,
    prepare_forward_window_commitment,
    prepare_forward_window_reveal,
    reconcile_account,
    target_weights_to_orders,
    verify_forward_evidence_window,
)
from .pettingzoo_env import MultiAgentSharpeArenaEnv, make_aec_env
from .portfolio_env import PortfolioEnv
from .preprocessing import (
    CANONICAL_PREPROCESSING,
    ExecutionNoiseConfig,
    PreprocessingConfig,
    describe_preprocessing,
    make_preprocessed_env,
)
from .realism import (
    CALM_CALIBRATION_CANDIDATE_KNOBS,
    DEFAULT_THRESHOLDS,
    RealismReport,
    certify_realism,
    stylized_facts,
)
from .regime_eval import evaluate_per_regime, radar_score
from .registration import register_envs
from .reward_misspecification import (
    MISSPECIFIED_PROXY_POLICIES,
    MISSPECIFIED_REWARDS,
    demonstrate_punishment,
    misspecification_gap,
)
from .rewards import (
    REWARD_SCHEMES,
    build_scheme_rubric,
    differential_sharpe,
    drawdown_penalized,
    list_reward_schemes,
    loss_averse,
    risk_aware,
    sortino,
    time_aversion_schedule,
    time_inhomogeneous_vol_aversion,
    turnover_penalized,
)
from .risk import CrossSectionalDeleverage, DrawdownStopper, TurbulenceHalt
from .sharpearena_py import (
    DataUnavailable,
    EngineFailure,
    InvalidArgument,
    InvalidJson,
    InvalidSalt,
    SharpeArenaError,
    TradingEnv,
    VecTradingEnv,
    decision_schema_json,
    score_run,
    validate_decision_json,
)
from .spaces import FlattenObservation, flat_dim, flatten_obs, unflatten_obs
from .strategy_generation import (
    CandidateRejection,
    GenerationResult,
    OllamaStrategyGenerator,
    StrategyCandidate,
    StrategyGenerator,
    StrategyProtocolError,
    StrategySearchPlan,
    StrategySearchRunner,
    evaluate_condition,
    parse_generated_pool,
    strategy_decision,
)
from .trace import SCHEMA_VERSION, RolloutTraceWriter, load_trace, trace_to_returns
from .vector import SharpeArenaVectorEnv
from .verifiers_env import (
    SharpeArenaVerifiersEnv,
    build_rubric,
    load_environment,
    mandate_reward,
)
from .wrappers import (
    CausalNormalizeObservation,
    CausalNormalizeReward,
    FrameStack,
    RecordEpisodeStatistics,
    TimeLimit,
)
from .wrappers_vector import (
    VectorCausalNormalizeObservation,
    VectorRecordEpisodeStatistics,
)

# Farama plugin convention: register the versioned env IDs at import time (idempotent).
register_envs()

__all__ = [
    "TradingEnv",
    "VecTradingEnv",
    "DataUnavailable",
    "EngineFailure",
    "InvalidArgument",
    "InvalidJson",
    "InvalidSalt",
    "SharpeArenaError",
    "SpecHashMismatch",
    "EXPECTED_SPEC_HASH",
    "check_spec_hash",
    "score_run",
    "decision_schema_json",
    "validate_decision_json",
    "BenchBridgeError",
    "compile_benchmark_evidence",
    "DatasetSpec",
    "DecisionModel",
    "DecisionResponseError",
    "EvidenceJournal",
    "FieldCell",
    "FieldPlan",
    "InferenceOutcome",
    "InferenceResult",
    "LocalAgentError",
    "LocalFieldRunner",
    "ModelHttpError",
    "ModelIdentity",
    "ModelResponseError",
    "ModelRunConfig",
    "ModelTransportError",
    "OllamaClient",
    "OpenAICompatibleClient",
    "PromptRenderer",
    "SamplingConfig",
    "load_identity_manifest",
    "DeclaredCandidateLineage",
    "IdeaProvenance",
    "bind_idea_source",
    "CandidateRejection",
    "GenerationResult",
    "OllamaStrategyGenerator",
    "StrategyCandidate",
    "StrategyGenerator",
    "StrategyProtocolError",
    "StrategySearchPlan",
    "StrategySearchRunner",
    "evaluate_condition",
    "parse_generated_pool",
    "strategy_decision",
    "AlpacaMarketData",
    "AlpacaPaperBroker",
    "BinancePublicData",
    "ForwardEvidenceJournal",
    "InMemoryPaperBroker",
    "PaperAccount",
    "PaperOrder",
    "PaperRiskConfig",
    "PaperRiskGuard",
    "PaperTradingSession",
    "prepare_forward_window_commitment",
    "prepare_forward_window_reveal",
    "LIFECYCLE_STATES",
    "STATE_FILLED",
    "STATE_PREPARED",
    "STATE_RECONCILED_ABSENT",
    "STATE_RECONCILED_ACCEPTED",
    "STATE_SUBMISSION_UNKNOWN",
    "AccountSnapshot",
    "ForwardWindowIdentity",
    "LifecycleError",
    "LifecycleStore",
    "OrderLifecycle",
    "SubmissionUnknown",
    "bind_forward_window",
    "forward_window_from_preimage",
    "make_forward_commitment",
    "reconcile_account",
    "target_weights_to_orders",
    "verify_forward_evidence_window",
    "SharpeArenaEnv",
    "SharpeArenaVectorEnv",
    "LookaheadGuard",
    "LookaheadViolation",
    "guarded",
    "wrap_policy",
    "SCHEMA_VERSION",
    "RolloutTraceWriter",
    "load_trace",
    "trace_to_returns",
    "RunMetrics",
    "cost_adjusted_score",
    "check_env",
    "check_determinism_across_constructors",
    "TimeLimit",
    "CausalNormalizeObservation",
    "CausalNormalizeReward",
    "FrameStack",
    "RecordEpisodeStatistics",
    "train_test_seeds",
    "evaluate_seeds",
    "generalization_gap",
    "cross_regime_transfer",
    "SharpeArenaVerifiersEnv",
    "load_environment",
    "build_rubric",
    "build_scenario_dataset",
    "seed_ranges_disjoint",
    "parse_decision",
    "VectorCausalNormalizeObservation",
    "VectorRecordEpisodeStatistics",
    "flatten_obs",
    "unflatten_obs",
    "flat_dim",
    "FlattenObservation",
    "ExecutionNoiseWrapper",
    "Mandate",
    "sample_mandate",
    "mandate_text",
    "mandate_breach",
    "mandate_from_dict",
    "validate_mandate",
    "mandate_reward",
    "run_baselines",
    "leaderboard_markdown",
    "deflated_sharpe_ci",
    "paired_dsr_diff",
    "pairwise_significance",
    "significance_markdown",
    "to_minari",
    "to_minari_train_test",
    "MultiAgentSharpeArenaEnv",
    "make_aec_env",
    "EndogenousMarketEnv",
    "CheckpointableEnv",
    "CheckpointState",
    "SharpeArenaFuncEnv",
    "CurriculumEnv",
    "regime_curriculum",
    "AdaptiveScheduler",
    "AdaptiveCurriculumEnv",
    "PreprocessingConfig",
    "ExecutionNoiseConfig",
    "CANONICAL_PREPROCESSING",
    "make_preprocessed_env",
    "describe_preprocessing",
    "EffectiveConfigError",
    "check_env_effective_config",
    "env_effective_config",
    "merge_effective_configs",
    "resolved_scenario_seed",
    "scenario_fingerprint",
    "EVAL_SEEDS",
    "evaluate_eval_set",
    "assert_no_regression",
    "EVAL_SET_VERSION",
    "sealed_eval_seeds",
    "REWARD_SCHEMES",
    "list_reward_schemes",
    "build_scheme_rubric",
    "differential_sharpe",
    "sortino",
    "drawdown_penalized",
    "turnover_penalized",
    "loss_averse",
    "risk_aware",
    "time_inhomogeneous_vol_aversion",
    "time_aversion_schedule",
    "CausalIndicatorObservation",
    "INDICATORS",
    "DEFAULT_INDICATORS",
    "DrawdownStopper",
    "TurbulenceHalt",
    "CrossSectionalDeleverage",
    "FailureMode",
    "classify_episode_failure",
    "FailureRollup",
    "rollup_failure_modes",
    "SyntheticNewsObservation",
    "news_series",
    "DiscreteAction",
    "SpreadObservation",
    "KalmanSpreadObservation",
    "MinVariancePolicy",
    "MaxSharpePolicy",
    "KellyVolTargetPolicy",
    "BEHAVIORAL_POLICIES",
    "DispositionEffectPolicy",
    "OverconfidentPolicy",
    "evaluate_per_regime",
    "radar_score",
    "PortfolioEnv",
    "MarketMakingEnv",
    "MMParams",
    "analytically_optimal_policy",
    "closed_form_reference_policy",
    "fixed_spread_policy",
    "mm_regret",
    "ExecutionEnv",
    "execution_quality",
    "twap_policy",
    "immediate_policy",
    "calibrated_forecast",
    "ForecastChannelObservation",
    "forecast_skill_curve",
    "MultiTimescaleMomentum",
    "RollingCovarianceObservation",
    "KalmanTrendObservation",
    "TimeToHorizonObservation",
    "CounterfactualInfo",
    "find_continuous_blocks",
    "block_windows",
    "sample_block_window",
    "make_block_env",
    "LiquidationCascadeEnv",
    "cascade_survived",
    "cascade_summary",
    "LOBMarketEnv",
    "symmetric_quote_policy",
    "noise_trader_policy",
    "MISSPECIFIED_REWARDS",
    "MISSPECIFIED_PROXY_POLICIES",
    "misspecification_gap",
    "demonstrate_punishment",
    "stylized_facts",
    "certify_realism",
    "RealismReport",
    "DEFAULT_THRESHOLDS",
    "CALM_CALIBRATION_CANDIDATE_KNOBS",
    "register_envs",
    # Adverse selection: the maker-side risk a single-agent env cannot express.
    "AdverseSelectionParams",
    "AdverseSelectionReport",
    "MetaOrder",
    "MakerMarkout",
    "Fill",
    "EndogenousImpact",
    "run_adverse_selection",
    "compare_informed_vs_uninformed",
    "compare_endogenous_arms",
    "informed_displacement",
    "fill_markout",
    # Manipulation: a red-team diagnostic on the impact model, not a strategy.
    "ManipulationParams",
    "ManipulationResult",
    "BoundaryReport",
    "SizeResponse",
    "run_manipulation_probe",
    "impact_boundary_sweep",
    "size_response",
    "pump_and_dump_schedule",
    "momentum_follower_policy",
    "DISCLAIMER",
    "AsymmetricSchedule",
    "AsymmetricResult",
    "asymmetric_round_trip_schedule",
    "run_asymmetric_probe",
    # Ecology: strategies compete and populations shift.
    "run_ecology",
    "population_table",
    "replicator_step",
    "allocate_seats",
    "mutating_innovator",
    "steady_shocks",
    "regime_shocks",
    "liquidity_shocks",
    "baseline_species",
    "market_payoffs",
    "competition_payoffs",
    "detect_coalitions",
    "classify_outcomes",
    # Deferred resolution: predictions that settle after the episode ends.
    "POINT",
    "PROBABILITY",
    "CATEGORICAL",
    "NORMAL",
    "DIRECTION",
    "INTERVAL",
    "POINT_ERRORS",
    "BINARY_BRIER",
    "BINARY_LOG",
    "CATEGORICAL_BRIER",
    "CATEGORICAL_LOG",
    "NORMAL_CRPS",
    "DIRECTION_ACCURACY",
    "INTERVAL_SCORE",
    "FORECAST_CONTRACT_SCHEMA_VERSION",
    "FORECAST_EVIDENCE_SCHEMA_VERSION",
    "ForecastContract",
    "ForecastContractError",
    "DeferredDesk",
    "Claim",
    "Outcome",
    "LeakedResolution",
    "UnresolvedClaim",
    "ClaimRejected",
    "resolve_claims",
    "outcomes_from_series",
    "claims_from_json",
    "score_claim",
    "summarize",
    # Prospective forecast evidence, revisions, exposure, and lifecycle.
    "ELIGIBLE",
    "LATE",
    "REJECTED",
    "PENDING",
    "RESOLVED",
    "CANCELLED",
    "ForecastRunIdentity",
    "InformationExposure",
    "ForecastRevision",
    "ForecastResolution",
    "ForecastEvidence",
    "ForecastEvidenceError",
    "ForecastLedger",
    "forecast_evidence_from_json",
    "write_forecast_evidence",
]
__version__ = "0.23.0"
